from .base_model import BaseFeatureModel
from pydantic import Field
from typing import Optional, Dict, Any, List
from datetime import datetime
from enum import Enum
import re


class NotificationType(str, Enum):
    WELCOME = "welcome"
    RSU_VESTING = "rsu_vesting"
    RSU_GRANT = "rsu_grant"
    OPTIONS_VESTING = "options_vesting"
    PORTFOLIO_UPDATE = "portfolio_update"
    SYSTEM = "system"
    FEATURE = "feature"


class DisplayType(str, Enum):
    POPUP = "popup"
    BELL = "bell"
    BOTH = "both"


class DismissalType(str, Enum):
    ONCE = "once"              # Show once per user, then never again
    UNTIL_CLICKED = "until_clicked"  # Keep showing until user dismisses
    AUTO_EXPIRE = "auto_expire"      # Auto-hide after expires_at


class DistributionType(str, Enum):
    PUSH = "push"      # Generate for all users immediately on template creation
    PULL = "pull"      # Generate when user fetches notifications (on login)
    TRIGGER = "trigger"  # Generated by event-based logic (RSU vesting, etc.)


class NotificationStatus(str, Enum):
    UNREAD = "unread"
    READ = "read"
    ARCHIVED = "archived"


def substitute_variables(template_string: str, variables: Dict[str, Any]) -> str:
    """
    Substitute {variable_name} placeholders in template string.
    Supports default values: {variable_name:default_value}
    """
    def replacer(match):
        full_match = match.group(1)
        if ":" in full_match:
            var_name, default = full_match.split(":", 1)
        else:
            var_name = full_match
            default = f"[{var_name}]"  # Show placeholder if missing
        return str(variables.get(var_name, default))

    return re.sub(r'\{([^}]+)\}', replacer, template_string)


def extract_variables(template_string: str) -> List[str]:
    """Extract variable names from template string"""
    matches = re.findall(r'\{([^}:]+)(?::[^}]*)?\}', template_string)
    return list(set(matches))


class NotificationTemplate(BaseFeatureModel):
    """Template for generating user notifications"""
    template_id: str = Field(..., description="Unique identifier for this template")
    notification_type: NotificationType = Field(..., description="Type of notification this template generates")

    # Content with variable placeholders
    title_template: str = Field(..., min_length=1, max_length=200,
        description="Title with {variable} placeholders")
    message_template: str = Field(..., min_length=1, max_length=1000,
        description="Message with {variable} placeholders")

    # Variable definitions
    available_variables: List[str] = Field(default_factory=list,
        description="List of variable names available for substitution")
    required_variables: List[str] = Field(default_factory=list,
        description="Variables that MUST be provided when generating from this template")

    # Distribution configuration
    distribution_type: DistributionType = Field(default=DistributionType.PULL,
        description="How notifications are distributed to users")

    # Display configuration
    display_type: DisplayType = Field(default=DisplayType.BOTH)
    dismissal_type: DismissalType = Field(default=DismissalType.ONCE)
    expires_in_days: Optional[int] = Field(default=None,
        description="Days until notification expires (from user generation time)")
    link_url: Optional[str] = Field(default=None)
    link_text: Optional[str] = Field(default="Check it out")

    # Lifecycle
    is_active: bool = Field(default=True, description="Whether template is currently active")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    created_by: Optional[str] = Field(default=None, description="Admin user ID who created")

    # Push distribution tracking
    push_completed_at: Optional[datetime] = Field(default=None,
        description="When push distribution completed (for PUSH type)")
    push_user_count: Optional[int] = Field(default=None,
        description="Number of users who received push notification")


# Default templates seeded on startup
DEFAULT_NOTIFICATION_TEMPLATES = [
    {
        "template_id": "welcome",
        "notification_type": NotificationType.WELCOME,
        "title_template": "Welcome to Vestika!",
        "message_template": "Welcome {user_name}! Start by creating your first portfolio to track your investments.",
        "available_variables": ["user_name"],
        "required_variables": [],
        "distribution_type": DistributionType.TRIGGER,
        "display_type": DisplayType.BOTH,
        "dismissal_type": DismissalType.ONCE,
        "is_active": True
    },
    {
        "template_id": "rsu_vesting",
        "notification_type": NotificationType.RSU_VESTING,
        "title_template": "RSU Vesting Event",
        "message_template": "Your RSUs for {symbol} have vested! {units} units are now available in your {account_name} account.",
        "available_variables": ["symbol", "units", "vest_date", "account_name"],
        "required_variables": ["symbol", "units", "account_name"],
        "distribution_type": DistributionType.TRIGGER,
        "display_type": DisplayType.BELL,
        "dismissal_type": DismissalType.ONCE,
        "is_active": True
    },
    {
        "template_id": "rsu_grant",
        "notification_type": NotificationType.RSU_GRANT,
        "title_template": "New RSU Grant",
        "message_template": "You've been granted {units} RSU units of {symbol} in your {account_name} account.",
        "available_variables": ["symbol", "units", "grant_date", "account_name"],
        "required_variables": ["symbol", "units", "account_name"],
        "distribution_type": DistributionType.TRIGGER,
        "display_type": DisplayType.BELL,
        "dismissal_type": DismissalType.ONCE,
        "is_active": True
    }
]


class Notification(BaseFeatureModel):
    user_id: str = Field(..., description="Firebase UID of the user")
    type: NotificationType = Field(..., description="Type of notification")
    title: str = Field(..., min_length=1, max_length=200, description="Notification title")
    message: str = Field(..., min_length=1, max_length=1000, description="Notification message")
    status: NotificationStatus = Field(default=NotificationStatus.UNREAD, description="Read status")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional data for the notification")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="When notification was created")
    read_at: Optional[datetime] = Field(default=None, description="When notification was read")
    archived_at: Optional[datetime] = Field(default=None, description="When notification was archived")
    # Template tracking
    template_id: Optional[str] = Field(default=None, description="ID of template this notification was generated from")
    # Display configuration fields
    display_type: Optional[DisplayType] = Field(default=None, description="How to display: popup, bell, or both")
    dismissal_type: Optional[DismissalType] = Field(default=None, description="When to stop showing: once, until_clicked, auto_expire")
    expires_at: Optional[datetime] = Field(default=None, description="When notification auto-expires (for auto_expire dismissal)")
    link_url: Optional[str] = Field(default=None, description="URL to navigate to (internal route or external)")
    link_text: Optional[str] = Field(default=None, description="Button text for the link (default: 'Check it out')")
    # Legacy field - kept for backward compatibility with existing feature notifications
    feature_id: Optional[str] = Field(default=None, description="Unique identifier for the feature (to prevent duplicates)")

    @classmethod
    def create_welcome_notification(cls, user_id: str, user_name: str) -> 'Notification':
        """Create a welcome notification for a new user"""
        return cls(
            user_id=user_id,
            type=NotificationType.WELCOME,
            title="Welcome to Vestika!",
            message=f"Welcome {user_name}! Start by creating your first portfolio to track your investments.",
            metadata={
                "is_welcome": True,
                "user_name": user_name
            }
        )

    @classmethod
    def create_rsu_vesting_notification(
        cls,
        user_id: str,
        symbol: str,
        units: float,
        vest_date: str,
        account_name: str
    ) -> 'Notification':
        """Create an RSU vesting notification"""
        return cls(
            user_id=user_id,
            type=NotificationType.RSU_VESTING,
            title="RSU Vesting Event",
            message=f"Your RSUs for {symbol} have vested! {units} units are now available in your {account_name} account.",
            metadata={
                "symbol": symbol,
                "units": units,
                "vest_date": vest_date,
                "account_name": account_name,
                "event_type": "vesting"
            }
        )

    @classmethod
    def create_rsu_grant_notification(
        cls,
        user_id: str,
        symbol: str,
        units: float,
        grant_date: str,
        account_name: str
    ) -> 'Notification':
        """Create an RSU grant notification"""
        return cls(
            user_id=user_id,
            type=NotificationType.RSU_GRANT,
            title="New RSU Grant",
            message=f"You've been granted {units} RSU units of {symbol} in your {account_name} account.",
            metadata={
                "symbol": symbol,
                "units": units,
                "grant_date": grant_date,
                "account_name": account_name,
                "event_type": "grant"
            }
        )

    @classmethod
    def create_feature_notification(
        cls,
        user_id: str,
        feature_id: str,
        title: str,
        message: str,
        display_type: DisplayType = DisplayType.BOTH,
        dismissal_type: DismissalType = DismissalType.ONCE,
        expires_at: Optional[datetime] = None,
        link_url: Optional[str] = None,
        link_text: Optional[str] = None
    ) -> 'Notification':
        """Create a feature announcement notification"""
        return cls(
            user_id=user_id,
            type=NotificationType.FEATURE,
            title=title,
            message=message,
            display_type=display_type,
            dismissal_type=dismissal_type,
            expires_at=expires_at,
            link_url=link_url,
            link_text=link_text or "Check it out",
            feature_id=feature_id,
            metadata={
                "feature_id": feature_id
            }
        )
